CATALOGUE_HOST: catalogue.backend-{{ env }}.daws86s.site
REDIS_HOST: redis.daws86s.site
MONGODB_HOST: mongodb.daws86s.site
USER_HOST: user.backend-{{ env }}.daws86s.site
CART_HOST: cart.backend-{{ env }}.daws86s.site
SHIPPING_HOST: shipping.backend-{{ env }}.daws86s.site
MYSQL_HOST: mysql.daws86s.site
PAYMENT_HOST: payment.backend-{{ env }}.daws86s.site
